# Generated by Django 4.0.5 on 2022-06-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
